name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build executable
        run: |
          python bundle.py
      - name: Get version
        id: get_version
        run: |
          version=$(python -c "import importlib.util; spec = importlib.util.spec_from_file_location('version', 'pdf_comment_viewer/version.py'); version = importlib.util.module_from_spec(spec); spec.loader.exec_module(version); print(version.__version__)")
          echo "Building version: $version"
          echo "version=$version" >> $GITHUB_ENV
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDFCommentViewer-Windows
          path: dist/PDFCommentViewer.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build executable
        run: |
          python -m PyInstaller bundle_config.py
      - name: Create DMG
        run: |
          # Create directory for the app
          mkdir -p dist/dmg
          cp -R "dist/PDFCommentViewer.app" dist/dmg/
          # Create .dmg file
          hdiutil create -volname "PDF Comment Viewer" -srcfolder dist/dmg -ov -format UDZO dist/PDFCommentViewer.dmg
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDFCommentViewer-MacOS
          path: dist/PDFCommentViewer.dmg

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build executable
        run: |
          python -m PyInstaller bundle_config.py
      - name: Create tarball
        run: |
          cd dist
          tar -czvf pdf_comment_viewer_linux.tar.gz pdf_comment_viewer
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDFCommentViewer-Linux
          path: dist/pdf_comment_viewer_linux.tar.gz

  create-release:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: "PDF Comment Viewer v${{ env.version }}"
          body: |
            PDF Comment Viewer version ${{ env.version }}
            
            ## Changes in this release
            - See commit history for details
            
            ## Files
            - Windows: PDFCommentViewer-${{ env.version }}.exe
            - macOS: PDFCommentViewer-${{ env.version }}.dmg
            - Linux: pdf_comment_viewer-${{ env.version }}.tar.gz
          draft: false
          prerelease: false
      - name: Upload Windows Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: PDFCommentViewer-Windows/PDFCommentViewer-${{ env.version }}.exe
          asset_name: PDFCommentViewer-${{ env.version }}-Windows.exe
          asset_content_type: application/octet-stream
      - name: Upload macOS Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: PDFCommentViewer-MacOS/PDFCommentViewer-${{ env.version }}.dmg
          asset_name: PDFCommentViewer-${{ env.version }}-MacOS.dmg
          asset_content_type: application/octet-stream
      - name: Upload Linux Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: PDFCommentViewer-Linux/pdf_comment_viewer-${{ env.version }}.tar.gz
          asset_name: pdf_comment_viewer-${{ env.version }}-Linux.tar.gz
          asset_content_type: application/gzip